### ISSUE TITLE
Term synonym PHP warning

### ISSUE THREAD

**Issue by BrElio** [searchwp/searchwp-term-synonyms#1]
The plugin generates a warning when there are no synonyms set up:

Warning: Invalid argument supplied for foreach() in .../wp-content/plugins/searchwp-term-synonyms/searchwp-term-synonyms.php on line 248

**Comment by jchristopher** [comment]
I can't actually reproduce this issue, and there's a check in place for an empty array here:

https://github.com/searchwp/searchwp-term-synonyms/blob/master/searchwp-term-synonyms.php#L247

I'm wondering if we can get a clone of their site to see if the `empty()` check is not working properly?

**Comment by BrElio** [comment]
It does happen to me as well. It looks like the option 'swp_termsyn_options' contains a string - 'SearchWP Term Synonyms' instead of an empty array

**Comment by jchristopher** [comment]
Ah! That's a *great* catch! I wonder how that happened — I'll get a check for an `array` in there as well. Thanks Elio!
